export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR';

export const GET_CONTACT_ID = 'GET_CONTACT_ID';
export const CLOSE_MODAL = 'CLOSE_MODAL';