export const CHANGE_FIELD = 'CHANGE_FIELD';
export const SEND_NEW_CONTACT_REQUEST = 'SEND_NEW_CONTACT_REQUEST';
export const SEND_NEW_CONTACT_SUCCESS = 'SEND_NEW_CONTACT_SUCCESS';
export const SEND_NEW_CONTACT_ERROR = 'SEND_NEW_CONTACT_ERROR';

export const GET_CONTACTS_REQUEST = 'GET_CONTACTS_REQUEST';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR';

export const SHOW_MODAL_FULL_CONTACT = 'SHOW_MODAL_FULL_CONTACT';