export const CHANGE_FIELD = 'CHANGE_FIELD';
export const SEND_NEW_CONTACT_REQUEST = 'SEND_NEW_CONTACT_REQUEST';
export const SEND_NEW_CONTACT_SUCCESS = 'SEND_NEW_CONTACT_SUCCESS';
export const SEND_NEW_CONTACT_ERROR = 'SEND_NEW_CONTACT_ERROR';